from django.urls import path
from home import views
urlpatterns = [
    path('',views.index),
    path('index',views.index),
    path('brands',views.brands),
    path('about',views.about),
    path('privacy',views.privacy),
    path('cart',views.cart),
    path('checkout',views.checkout),
    path('api/cart_items',views.cart_api),
    path('myprofile',views.myprofile),  
    path('wishlist',views.wishlist),  
    path('orders',views.order),
    path('login',views.login_user),
    path('signup',views.signup),
    path('logout',views.logout_user),
    path('productlisting',views.productlisting),
    path('test',views.test),
    path('api',views.api),
    path('products',views.prod_page),
    path('api/product',views.api_product),
    path('api/featured',views.api_featured),
    path('api/addcart',views.cart_add),
    path('api/cartcount',views.count_cart),
]
