# Generated by Django 4.1.2 on 2022-11-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('pid', models.TextField(default='', primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=200)),
                ('price', models.TextField(default='', max_length=6)),
                ('mrp', models.TextField(default='', max_length=6)),
                ('delivery', models.TextField(default='', max_length=2)),
                ('desc', models.TextField(default='', max_length=500)),
                ('images', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
