# Generated by Django 4.1.2 on 2022-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
