# Generated by Django 4.1.2 on 2022-11-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delivery',
            field=models.TextField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.TextField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.TextField(default='', max_length=6),
        ),
    ]
