# Generated by Django 4.1.2 on 2022-11-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_delivery_products_desc_products_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='delivery',
            field=models.IntegerField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='mrp',
            field=models.IntegerField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default='', max_length=6),
        ),
    ]
