# Generated by Django 4.1.2 on 2022-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_products_delivery_alter_products_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='delivery',
            field=models.TextField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='mrp',
            field=models.TextField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.TextField(default='', max_length=6),
        ),
    ]
