# Generated by Django 4.1.2 on 2022-11-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_products_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.TextField(default='202211231019403254', primary_key=True, serialize=False),
        ),
    ]
