# Generated by Django 4.1.2 on 2022-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_products_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
