# Generated by Django 4.1.2 on 2022-11-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_featured_alter_products_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('user_name', models.TextField(default='', primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
    ]
