# Generated by Django 4.1.2 on 2022-11-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart_items',
        ),
    ]
